"""add_room_id_to_chats

Revision ID: 94614a3cf24c
Revises: c1e9b8c16862
Create Date: 2024-06-14 09:16:49.185540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94614a3cf24c'
down_revision: Union[str, None] = 'c1e9b8c16862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('room_id', sa.String(length=36), nullable=False, comment='チャットroomのID-チャットiframe取得時に生成されるID'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'room_id')
    # ### end Alembic commands ###
