"""add_user_to_chat_messages

Revision ID: c1e9b8c16862
Revises: d14f4c6a8edb
Create Date: 2024-06-12 10:27:27.655050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c1e9b8c16862'
down_revision: Union[str, None] = 'd14f4c6a8edb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('user_id', sa.Integer(), nullable=True, comment='ユーザID'))
    op.create_foreign_key(None, 'chat_messages', 'users', ['user_id'], ['id'])
    op.alter_column('chats', 'responsed_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               comment='返信日時',
               existing_comment='開始日時')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'responsed_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               comment='開始日時',
               existing_comment='返信日時')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_column('chat_messages', 'user_id')
    # ### end Alembic commands ###
