"""create_chat

Revision ID: d14f4c6a8edb
Revises: 3d8ddcc504fe
Create Date: 2024-06-02 13:45:09.572323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd14f4c6a8edb'
down_revision: Union[str, None] = '3d8ddcc504fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('uuid', sa.String(length=36), nullable=False, comment='UUID'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='ユーザID'),
    sa.Column('corporation_id', sa.Integer(), nullable=False, comment='企業ID'),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='開始日時'),
    sa.Column('responsed_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='開始日時'),
    sa.Column('closed_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='終了日時'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['corporation_id'], ['corporations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('uuid', sa.String(length=36), nullable=False, comment='UUID'),
    sa.Column('chat_id', sa.Integer(), nullable=False, comment='チャットID'),
    sa.Column('sender', sa.Integer(), nullable=False, comment='送信者 1:チャット質問者 2:企業回答者(ユーザー)'),
    sa.Column('body', sa.Text(), nullable=False, comment='メッセージ内容'),
    sa.Column('send_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='送信日時'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_messages')
    op.drop_table('chats')
    # ### end Alembic commands ###
