"""drop_chat_column

Revision ID: ebb7e16e3f7e
Revises: 429b72f729b9
Create Date: 2024-06-15 15:13:42.795901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ebb7e16e3f7e'
down_revision: Union[str, None] = '429b72f729b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'closed_at')
    op.drop_column('chats', 'responsed_at')
    op.drop_column('chats', 'started_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('started_at', mysql.TIMESTAMP(), nullable=False, comment='開始日時'))
    op.add_column('chats', sa.Column('responsed_at', mysql.TIMESTAMP(), nullable=True, comment='返信日時'))
    op.add_column('chats', sa.Column('closed_at', mysql.TIMESTAMP(), nullable=True, comment='終了日時'))
    # ### end Alembic commands ###
